function Leroy = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LEROY = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  LEROY = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Leroy = importfile("E:\Studium\M2-SeafloorGeodesy\Master2-SeafloorGeodesyUebung\4-Nicho\2301-2303-Leroy.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2021-07-09 10:13:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["date", "ID", "range_ID", "bsl", "tt", "ssp1", "ssp2", "hrt1", "hrt2", "prs1", "prs2", "sal1", "sal2", "range", "TAT"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "date", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "date", "EmptyFieldRule", "auto");

% Import the data
Leroy = readtable(filename, opts);

end